"""empty message

Revision ID: 48942a7f739d
Revises: 9836b11cb74a
Create Date: 2023-03-02 17:25:46.019862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48942a7f739d'
down_revision = '9836b11cb74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.drop_column('likes', 'isLiked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('isLiked', sa.BOOLEAN(), nullable=True))
    op.drop_table('following')
    # ### end Alembic commands ###
