"""empty message

Revision ID: 4ddbd33d7001
Revises: 9836b11cb74a
Create Date: 2023-02-28 19:51:30.965910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ddbd33d7001'
down_revision = '9836b11cb74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'isLiked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('isLiked', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
