"""empty message

Revision ID: 7046fa6d257b
Revises: c1b70be1ee58
Create Date: 2023-03-04 09:59:03.044523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7046fa6d257b'
down_revision = 'c1b70be1ee58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.drop_table('following')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('main_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['main_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('main_id', 'followed_id')
    )
    op.drop_table('follows')
    # ### end Alembic commands ###
