"""empty message

Revision ID: 9836b11cb74a
Revises: d2c2d8165969
Create Date: 2023-02-28 19:42:53.455663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9836b11cb74a'
down_revision = 'd2c2d8165969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('background', sa.String(length=99999), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'background')
    # ### end Alembic commands ###
