"""empty message

Revision ID: d2c2d8165969
Revises: 0d4c95bcf66f
Create Date: 2023-02-21 10:57:10.898192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c2d8165969'
down_revision = '0d4c95bcf66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'created_at')
    # ### end Alembic commands ###
